name: Build and deploy demo

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-deploy:
    name: "Build and deploy"
    env:
      workspace_root: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools'
      qt_root_folder: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools'
      qt_version: '6.5.3'
      qt_target_arch: 'wasm_singlethread'
      target_folder: 'QtQuick3D-Tools'
      source_folder: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools/build/example'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'
          lfs: 'true'
 
      - name: Install tools
        shell: bash
        run: |
          sudo apt-get -y install brotli

      - name: Update CMake
        uses: lukka/get-cmake@latest

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Install Qt
        uses: jdpurcell/install-qt-action@v5
        with:
          version: ${{ env.qt_version }}
          target: 'wasm'
          arch: ${{ env.qt_target_arch }}
          modules: 'qtquick3d qtshadertools'
          dir: ${{ env.qt_root_folder }}
          use-naqt: true
          setup-python: false

      - name: CMake Build
        shell: bash
        run: |
          make web \
            QT_VERSION=${{ env.qt_version }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtQuick3D-Tools
          path: ${{ env.source_folder }}
